### ISSUE TITLE
ImportError: cannot import name 'CRS' from 'pyproj' 

### ISSUE THREAD

**Issue by devquercus** [corteva/rioxarray#386]
I am getting the following error message when I am importing the rioxarray library.

Has anyone came across the same issue?
How can I fix it?

**Comment by snowman2** [comment]
Please fill out this template:

#### Installation method/steps
 - Installation method (conda, pip, from source, etc...)
 - Please provide all commands/steps you used to install rioxarray and GDAL/rasterio.

#### Environment Information
 - rioxarray version you are attempting to install
 - pyproj version (`python -c "import pyproj; print(pyproj.__version__)"`)
 - rasterio version (`rio --version`)
 - GDAL version (`rio --gdal-version`)
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)

**Comment by snowman2** [comment]
I believe it is related to this: 
- https://stackoverflow.com/questions/59658167/cannot-import-name-crs-from-pyproj-for-using-the-osmnx-library
- https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it
```
conda config --prepend channels conda-forge
conda config --set channel_priority strict
```

Going to close due to lack of details. Feel free to add more details if this doesn't resolve the issue for you.
