### ISSUE TITLE
Access to original raster dtype?

### ISSUE THREAD

**Issue by chapmanjacobd** [corteva/rioxarray#431]
Is there a way to access the embedded dtype ?

`rast.rio.dtype` does not seem to exist. Would a PR which adds that property be accepted? (Or maybe a better name would be `rast.rio.encoded_dtype` ?)

As an aside: The behavior of `rast.rio.encoded_nodata` also seems a bit strange? From reading the [documentation](https://corteva.github.io/rioxarray/stable/getting_started/nodata_management.html#Example-of-loading-unmaksed-data) it seems like one would have to do `rast.rio.encoded_nodata or rast.rio.nodata` in order to pull out the original nodata value for both unmasked and masked data

**Comment by snowman2** [comment]
> The behavior of rast.rio.encoded_nodata also seems a bit strange? From reading the documentation it seems like one would have to do rast.rio.encoded_nodata or rast.rio.nodata in order to pull out the original nodata value for both unmasked and masked data

It is an interesting paradigm due to how `xarray` works. It all depends on your use case. When loading the data with `mask_and_scale=True`, it is useful for the code to use `rio.nodata` and get `NaN` back to indicate that the nodata values are `NaN`. It is also useful to know the original nodata value when writing the data back to a file (can help with the original dtype), thus `rio.encoded_nodata` exists.

**Comment by snowman2** [comment]
Currently, the `dtype` is stored in `encoding`:
```python
>>> import rioxarray
>>> rds = rioxarray.open_rasterio("cint16.tif", mask_and_scale=True)
>>> rds.encoding
{'dtype': 'complex64', 'scale_factor': 1.0, 'add_offset': 0.0, '_FillValue': 0.0, 'grid_mapping': 'spatial_ref', 'source': 'cint16.tif', 'rasterio_dtype': 'complex_int16'}
>>> rds.encoding["dtype"]
'complex64'
>>> rds.encoding["rasterio_dtype"]
'complex_int16'
```

```
