### ISSUE TITLE
Segfault when using MemoryFile objects

### ISSUE THREAD

**Issue by mraspaud** [corteva/rioxarray#550]
#### Code Sample, a copy-pastable example if possible

```python
from matplotlib import pyplot
import rioxarray
from rasterio.io import MemoryFile

filename = "test.jp2"

def read_file(filename):
    with open(filename, "rb") as of:
        data = of.read()
        memfile = MemoryFile(data)
        src = memfile.open()
        proj = rioxarray.open_rasterio(src, chunks=2048)
        return proj.squeeze("band")

proj = read_file(filename)
proj.plot.imshow()
pyplot.show()
```

#### Problem description

The above results in a segmentation fault every time (at least on my laptop)

#### Expected Output

I expect the display of my data.

#### Environment Information

rioxarray (0.11.2.dev0) deps:
  rasterio: 1.2.10
    xarray: 2022.3.0
      GDAL: 3.4.2
      GEOS: None
      PROJ: None
 PROJ DATA: None
 GDAL DATA: None

Other python deps:
     scipy: 1.8.0
    pyproj: 3.3.1

System:
    python: 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:28:35) [GCC 9.4.0]
executable: /home/a001673/mambaforge/envs/satpy/bin/python
   machine: Linux-4.18.0-372.16.1.el8_6.x86_64-x86_64-with-glibc2.28

#### Installation method
 - from a fresh git clone, with `pip install -e .`

**Comment by mraspaud** [comment]
I suspect this is due to gdal's memory file object being disposed off before dask can make use of it...

**Comment by mraspaud** [comment]
Just for clarification and some context: The opening of the file and reading to put the data in the MemoryFile is of course contrived, and just comes from the fact that I need to be able to pass open files to rioxarray. In my case, I want to use fsspec in the background (https://filesystem-spec.readthedocs.io/en/latest/) so as to be able to read remote files on the fly.

**Comment by mraspaud** [comment]
But thanks a lot for the heads up on @djhoese 's amazing contribution :)

**Comment by snowman2** [comment]
> The example you provide does not seem to work (so passing a regular open file to open_rasterio):

Haven't tested that feature with dask ... looks like we need a patch to handle that.

**Comment by djhoese** [comment]
I think using `.load()` would go against what we generally try to do in Satpy which is to delay loading data until it is actually being computed.

**Comment by jamespolly** [comment]
I think my question is pertinent enough to this discussion to supplement rather than derail. My apologies if that's not the case.

***It seems like the file-like objects are being closed before lazy evaluation can go back to retrieve data from them when needed. Am I trying to do something not supported? Am I missing a critical step in opening these objects?***

I'm noticing differing behavior when opening NetCDF files via xarray vs. GeoTIFF files (not necessarily CoGs) via `rioxarray` when both file types are being opened from a private Google Cloud Storage bucket.

In both cases `fsspec` is used to open a file-like object, and handle the credentials info of the GCS bucket. 
In the case of reading NetCDF files with `xarray`:
```
    self._storage_options = {'token': /path/to/gcs/token.json}
    self._fs = fsspec.filesystem(self._protocol, **self._storage_options)
    with self._fs.open(load_path, **self._fs_open_args_load) as fs_file:
        ds = xr.open_dataset(fs_file, **self._load_args)
```
The above works fine and is totally behaving as I'd expect an `xarray.DataSet` to behave (e.g., `ds.my_var.plot()` works as expected).

In the case of `rioxarray` I have tried two methods, similar to the above, but with different errors. In both cases the `DataArray` opens, and I can even access the coordinate values, but accessing the information that would show up in a plot is not possible, resulting in different errors.

First method:
```
    self._storage_options = {'token': /path/to/gcs/token.json}
    with self._fs.open(load_path, **self._fs_open_args_load) as fs_file:
        da = rioxarray.open_rasterio(fs_file, **self._load_args)
```
Note the file successfully opens (see output at bottom of post). But when I try to do `da.plot()` the following error is generated:
```
RasterioIOError: Read or write failed. /vsipythonfilelike/ac46c1fd-[...], band 1: IReadBlock failed at X offset 0, Y offset 0: 
_TIFFPartialReadStripArray:Cannot read offset/size for strile around ~0
```

Second method:
```
    self._storage_options = {'token': /path/to/gcs/token.json}
    with self._fs.open(load_path, **self._fs_open_args_load) as fs_file:
        with rioxarray.open_rasterio(fs_file, **self._load_args) as riofile:
            da = riofile
```
Note the file successfully opens (see output at bottom of post). But when I try to do `da.plot()` the following error is generated:
```
ValueError: I/O operation on closed file.
Exception ignored in: 'rasterio._filepath.filepath_read'
Traceback (most recent call last):
  File "/home/jpolly/miniconda3/envs/windninja/lib/python3.9/site-packages/fsspec/spec.py", line 1539, in read
    raise ValueError("I/O operation on closed file.")
ValueError: I/O operation on closed file.
2022-07-30 10:35:05,431 - rasterio._env - INFO - GDAL signalled an error: err_no=4, msg="`/vsipythonfilelike/90de91e0-e95f-4215-9b07-28fdb4e2b2ee/90de91e0-e95f-4215-9b07-28fdb4e2b2ee' not recognized as a supported file format."
```

In full transparency I'm doing this through Kedro, which is a complicating factor, but my approach works with NetCDF files via `xarray` as shown above. Despite note being able to plot, both of these `rioxarray` approaches successfully open the file, e.g.:
```
In [4]: da
Out[4]: 
<xarray.DataArray (band: 1, y: 3612, x: 3612)>
[13046544 values with dtype=float32]
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 -92.0 -92.0 -92.0 -92.0 ... -91.0 -91.0 -91.0 -91.0
  * y            (y) float64 42.0 42.0 42.0 42.0 42.0 ... 41.0 41.0 41.0 41.0
    spatial_ref  int64 0
Attributes:
    LAYER_TYPE:          athematic
    RepresentationType:  *
    _FillValue:          -999999.0
    scale_factor:        1.0
    add_offset:          0.0
    long_name:           Layer_1
```

**Comment by snowman2** [comment]
#558 should address this: https://github.com/corteva/rioxarray/issues/550#issuecomment-1187572731

**Comment by snowman2** [comment]
> I think using `.load()` would go against what we generally try to do in Satpy which is to delay loading data until it is actually being computed.

From what I can tell, calling `.load()` is equivalent to the initial code snippet above:
```python
    with open(filename, "rb") as of:
        data = of.read()
```
Since the data is lazily loaded by `rioxarray.open_rasterio`, calling `.load()` is the only way to load in the data before closing the file handle in the current state of the code.

Ideas to improve this behavior are definitely welcome. It may be worth looking into how xarray handles this scenario as they may have found a solution for this.

**Comment by snowman2** [comment]
I think this is resolved. If something is missing still, please comment.
